### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Mikaela** [agateau/mup#1] opened 2014-12-31 15:44 UTC
Hi, I saw [your post on Planet Ubuntu](http://agateau.com/2014/mup-a-markup-previewer/) and it looked interesting and found these two issues from README.

First, possibly separate issue at first: there is no `requirements.txt` file for pip to install those Python modules.

And the second issue is that I don't think that the commands you suggest in README for installation are good.

> The best way to install it is to run as root:
> `python setup.py install --prefix=$desktop_install_dir`
> Where $desktop_install_dir is usually /usr.

`/usr` should be only for things installed from apt/<package manager> and if something is installed from elsewhere, it should be in `/usr/local` instead which is in `$PATH` by default. Usually `python setup.py install` should install there directly without flags or without root `python setup.py install --user` installs to `$HOME/.local` which is in `PYTHONPATH` by default.

> This won't work on Debian or Ubuntu however. On these systems, you should use:
> sudo python setup.py install --install-layout=deb

`--install-layout=deb` is not familiar flag to me, but I assume that it also installs to `/usr` or somewhere similar.

**Comment by agateau** [comment] 2014-12-31 17:47
Regarding requirements.txt: the problem is PyQt4 is not available via pip, so it makes having a requirements.txt less useful, what do you think?

I suggest to install to the desktop install dir because if MUP is not installed that way, its .desktop file won't be found by the desktop. At least that's what I remembered: I just tried again and realized KDE Plasma found MUP even if it is installed to `/usr/local`. Going to fix the instructions.

**Comment by agateau** [comment] 2014-12-31 17:54
Fixes are in the dev branch, do they make sense to you?

**Comment by Mikaela** [comment] 2014-12-31 19:12
> Regarding requirements.txt: the problem is PyQt4 is not available via pip, so it makes having a requirements.txt less useful, what do you think?

Oh, I didn't think about those missing from pypi.

> Fixes are in the dev branch, do they make sense to you?

I think so. Thanks :)

**Comment by agateau** [comment] 2015-01-01 14:54
Just merged the changes in.

**Closed as completed by agateau** 2015-01-01 14:54 UTC
